# routing поиска пользователей
rp_search_users:
    resource: routing/searchUsers.yml
    prefix:   /api/search
    type: rest

# routing поиска мест
rp_search_places:
    resource: routing/searchPlaces.yml
    prefix:   /api/search
    type: rest

# routing поиска событий
rp_search_events:
    resource: routing/searchEvent.yml
    prefix:   /api/search
    type: rest

# routing поиска стран
rp_search_country:
    resource: routing/searchCountry.yml
    prefix:   /api/search
    type: rest

# routing поиска городов
rp_search_city:
    resource: routing/searchCity.yml
    prefix:   /api/search
    type: rest

# routing поиска маркеров
rp_search_markers:
    resource: routing/searchMarkers.yml
    prefix:   /api/search
    type: rest

# routing поиска по сообщениям
rp_search_messages:
    resource: routing/searchChatMessage.yml
    prefix:   /api/search
    type: rest

# routing поиска
rp_search_common:
    resource: routing/searchCommon.yml
    prefix:   /api/search
    type: rest

# routing поиска постов ленты
rp_search_newsFeed:
    resource: routing/searchNewsFeed.yml
    prefix:   /api/search
    type: rest