services:
    # Сервис поискового движка
    rp_search.search.engine:
        class: Common\Core\Facade\Search\QueryFactory\SearchEngine
        arguments:
            - "@fos_elastica.index"
            - "@rp_search.search.query_factory"
            - "@rp_search.search.query_condition"
            - "@rp_search.search.query_filter"
            - "@rp_search.search.query_aggregation"
            - "@rp_search.search.query_script_field"
            - "@rp_search.search.query_sorting"
        calls:
            - [ setContainer, [ "@service_container" ] ]
            - [ setLogger, [ "@logger" ] ]

    # сервис поиского движка
    rp_search.search.query_factory:
        class: Common\Core\Facade\Search\QueryFactory\QueryFactory

    # сервис формирования условий поиска
    rp_search.search.query_condition:
        class: Common\Core\Facade\Search\QueryCondition\ConditionFactory

    # сервис создания фильтра для поиска
    rp_search.search.query_filter:
        class: Common\Core\Facade\Search\QueryFilter\FilterFactory

    # сервис создания фильтра для поиска
    rp_search.search.query_aggregation:
        class: Common\Core\Facade\Search\QueryAggregation\QueryAggregationFactory

    # сервис создания фильтра для поиска
    rp_search.search.query_script_field:
        class: Common\Core\Facade\Search\QueryScripting\QueryScriptFactory

    # сервис сортировки при поиске
    rp_search.search.query_sorting:
        class: Common\Core\Facade\Search\QuerySorting\QuerySortFactory

    # Базовый абстрактный поисковый сервис
    rp_search.search_service.base:
        class: RP\SearchBundle\Services\AbstractSearchService
        parent: rp_search.search.engine
        calls:
            - [ setCountryTransformer, [ "@rp_search.transform_interface.country" ] ]
            - [ setCityTransformer, [ "@rp_search.transform_interface.city" ] ]
            - [ setPeopleTransformer, [ "@rp_search.transform_interface.people" ] ]
            - [ setPlaceTypeTransformer, [ "@rp_search.transform_interface.placetype" ] ]
            - [ setTagNamesTransformer, [ "@rp_search.transform_interface.tagnames" ] ]
            - [ setChatMessagesTransformer, [ "@rp_search.transform_interface.chat_message" ] ]

    # Сервис поиска людей в базе еластика
    rp_search.search_service.people:
        class: RP\SearchBundle\Services\PeopleSearchService
        parent: rp_search.search_service.base

    # Сервис поиска мест в базе еластика
    rp_search.search_service.places:
        class: RP\SearchBundle\Services\PlacesSearchService
        parent: rp_search.search_service.base

    # Сервис общего поиска (маркеров и поиска по локации)
    rp_search.search_service.common:
        class: RP\SearchBundle\Services\CommonSearchService
        parent: rp_search.search_service.base

    # Сервис поиска событий
    rp_search.search_service.events:
        class: RP\SearchBundle\Services\EventsSearchService
        parent: rp_search.search_service.base

    # Сервис поиска стран
    rp_search.search_service.country:
        class: RP\SearchBundle\Services\CountrySearchService
        parent: rp_search.search_service.base

    # Сервис поиска городов
    rp_search.search_service.city:
        class: RP\SearchBundle\Services\CitySearchService
        parent: rp_search.search_service.base

    rp_search.search_service.chat_message:
        class: RP\SearchBundle\Services\ChatMessageSearchService
        parent: rp_search.search_service.base

    rp_search.transform_interface.base:
        class: RP\SearchBundle\Services\Transformers\AbstractTransformer
        calls:
            - [ setContainer, [ "@service_container" ] ]
            - [ setElasticaIndex, [ "@fos_elastica.index" ] ]

    rp_search.transform_interface.country:
        class: RP\SearchBundle\Services\Transformers\CountryTransformer
        parent: rp_search.transform_interface.base
        calls:
            - [ setSearchService, [ "@rp_search.search_service.country" ] ]

    rp_search.transform_interface.city:
        class: RP\SearchBundle\Services\Transformers\CityTransformer
        parent: rp_search.transform_interface.base
        calls:
            - [ setSearchService, [ "@rp_search.search_service.city" ] ]

    rp_search.transform_interface.people:
        class: RP\SearchBundle\Services\Transformers\PeopleTransformer
        parent: rp_search.transform_interface.base
        calls:
            - [ setSearchService, [ "@rp_search.search_service.people" ] ]

    rp_search.transform_interface.placetype:
        class: RP\SearchBundle\Services\Transformers\PlaceTypeTransformer
        parent: rp_search.transform_interface.base
        calls:
            - [ setSearchService, [ "@rp_search.search_service.places" ] ]

    rp_search.transform_interface.tagnames:
        class: RP\SearchBundle\Services\Transformers\TagNameTransformer
        parent: rp_search.transform_interface.base
        calls:
            - [ setSearchService, [ "@rp_search.search_service.common" ] ]

    rp_search.transform_interface.chat_message:
        class: RP\SearchBundle\Services\Transformers\ChatMessageTransformer
        parent: rp_search.transform_interface.base
        calls:
            - [ setSearchService, [ "@rp_search.search_service.chat_message" ] ]

    rp_search.search_service.news_feed.posts:
        class: RP\SearchBundle\Services\NewsFeedSearchService
        parent: rp_search.search_service.base