services:
    # Сервис поискового движка
    rp_search.search.engine:
        class: Common\Core\Facade\Search\QueryFactory\SearchEngine
        arguments:
            - "@fos_elastica.index"
            - "@rp_search.search.query_factory"
            - "@rp_search.search.query_condition"
            - "@rp_search.search.query_filter"
            - "@rp_search.search.query_aggregation"
            - "@rp_search.search.query_script_field"
            - "@rp_search.search.query_sorting"
        calls:
            - [ setContainer, [ "@service_container" ] ]
            - [ setLogger, [ "@logger" ] ]

    # сервис поиского движка
    rp_search.search.query_factory:
        class: Common\Core\Facade\Search\QueryFactory\QueryFactory

    # сервис формирования условий поиска
    rp_search.search.query_condition:
        class: Common\Core\Facade\Search\QueryCondition\ConditionFactory

    # сервис создания фильтра для поиска
    rp_search.search.query_filter:
        class: Common\Core\Facade\Search\QueryFilter\FilterFactory

    # сервис создания фильтра для поиска
    rp_search.search.query_aggregation:
        class: Common\Core\Facade\Search\QueryAggregation\QueryAggregationFactory

    # сервис создания фильтра для поиска
    rp_search.search.query_script_field:
        class: Common\Core\Facade\Search\QueryScripting\QueryScriptFactory

    # сервис сортировки при поиске
    rp_search.search.query_sorting:
        class: Common\Core\Facade\Search\QuerySorting\QuerySortFactory

    # Базовый абстрактный поисковый сервис
    rp_search.search_service.base:
        class: RP\SearchBundle\Services\AbstractSearchService
        parent: rp_search.search.engine

    # Сервис поиска людей в базе еластика
    rp_search.search_service.people:
        class: RP\SearchBundle\Services\PeopleSearchService
        parent: rp_search.search_service.base

    # Сервис поиска мест в базе еластика
    rp_search.search_service.places:
        class: RP\SearchBundle\Services\PlacesSearchService
        parent: rp_search.search_service.base

    # Сервис общего поиска (маркеров и поиска по локации)
    rp_search.search_service.common:
        class: RP\SearchBundle\Services\CommonSearchService
        parent: rp_search.search_service.base

    # Сервис поиска событий
    rp_search.search_service.events:
        class: RP\SearchBundle\Services\EventsSearchService
        parent: rp_search.search_service.base

    # Сервис поиска городов
    rp_search.search_service.city:
        class: RP\SearchBundle\Services\CitySearchService
        parent: rp_search.search_service.base