services:
    # Сервис поискового движка
    rp_search.search.engine:
        class: Common\Core\Facade\Search\QueryFactory\SearchEngine
        arguments:
            - "@fos_elastica.index"
            - "@rp_search.search.query_factory"
            - "@rp_search.search.query_condition"
            - "@rp_search.search.query_filter"
        calls:
            - [ setContainer, [ "@service_container" ] ]
            - [ setLogger, [ "@logger" ] ]

    # сервис поиского движка
    rp_search.search.query_factory:
        class: Common\Core\Facade\Search\QueryFactory\QueryFactory

    # сервис формирования условий поиска
    rp_search.search.query_condition:
        class: Common\Core\Facade\Search\QueryCondition\ConditionFactory

    # сервис создания фильтра для поиска
    rp_search.search.query_filter:
        class: Common\Core\Facade\Search\QueryFilter\FilterFactory

    # Базовый абстрактный поисковый сервис
    rp_search.search_service.base:
        class: RP\SearchBundle\Services\AbstractSearchService
        parent: rp_search.search.engine

    rp_search.search_service.people:
        class: RP\SearchBundle\Services\PeopleSearchService
        parent: rp_search.search_service.base

    #rp_common.search.elastica_to_model_transformer.user_profile:
    #    class: RP\Common\Reporting\Search\ElasticaResultTransformer
    #    arguments:
    #        - "@doctrine_mongodb"
    #        - RP\Common\Reporting\User\Document\UserProfileDocument
    #    calls:
    #        - [ "setPropertyAccessor", [ @fos_elastica.property_accessor ] ]
    #    tags:
    #        - { name: fos_elastica.elastica_to_model_transformer, index: rp, type: user }