# необходимо указать версию vagrant окружения
VAGRANTFILE_API_VERSION = "2"

# тут обязательно указываем название создаваемые машины под сервис
# поскольку это болванка сервиса то и название будет default
# когда на основе болванки мы начинаем создавать некий сервис
# желательно писать название сервиса,
# допустим под сервис поиска название было бы "search"
VAGRANT_MACHINE_NAME = "search"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos/7"
  config.ssh.insert_key = false

  config.vm.hostname = VAGRANT_MACHINE_NAME

  config.vm.define VAGRANT_MACHINE_NAME, primary: true do |default|

      default.vm.provider :virtualbox do |vb|
          vb.gui = false
          vb.customize ["modifyvm", :id, "--memory", "4096"]
      end

      # Networking options
      default.vm.network "private_network", type: "dhcp"
      default.vm.network "forwarded_port", guest: 80, host: 8080
  end

  config.vm.synced_folder "../vagrant/", "/home/vagrant/vagrant"
  config.vm.synced_folder "../www/", "/home/vagrant/www"
  config.vm.synced_folder "../www/vendor/", "/home/vagrant/www/vendor", disabled: true


  config.vm.provision "main install", type: "shell", path: "install.sh"
  config.vm.provision "nginx install", type: "shell", path: "services/nginx.sh"
  config.vm.provision "mongodb install", type: "shell", path: "services/mongodb.sh"
  config.vm.provision "php71 install", type: "shell", path: "services/php.sh"
  config.vm.provision "elasticsearch install", type: "shell", path: "services/elasticsearch.sh"
  config.vm.provision "copymover install", type: "shell", path: "services/copymover.sh"
  config.vm.provision "runner services", type: "shell", path: "services/runner.sh"

end