# Hide most inner properties from Symfony events aside from name
Symfony\Component\EventDispatcher\Event:
    exclusion_policy: ALL
    properties:
        name:
            expose: true
            type: string