# Elastica Configuration
fos_elastica:
    clients:
        default:
            host: '%elasticsearch.host%'
            port: '%elasticsearch.port%'
            logger: true
    serializer:
        serializer: jms_serializer
    default_manager: mongodb
    indexes:
        russianplace:
            client: default
            finder: ~
        russianplace_private:
            client: default
            finder: ~