jms_serializer:
    enable_short_alias: false
    handlers:
        datetime:
            default_format: "Y-m-d\\TH:i:sO" # ISO8601
            default_timezone: "UTC" # defaults to whatever timezone set in php.ini or via date_default_timezone_set
    metadata:
        cache: file
        debug: true
        file_cache:
            dir: '%kernel.cache_dir%/jms_serializer'
        auto_detection: true
        infer_types_from_doctrine_metadata: false
        directories:
            Symfony:
                namespace_prefix: "Symfony"
                path: "@CommonBundle/Resources/config/symfony"

    property_naming: ~