parameters:
    common.namespace: Common
    common.core.namespace: '%common.namespace%\Core'
services:
    # handler для передаче клиенту формата x-plist
    # данный формат используется только в IOS
    rp_common.plist_handler:
        class: '%common.core.namespace%\Serializer\View\PlistViewHandler'

    # handler для передаче клиенту формата rss ленты
    rp_common.rss_handler:
        class: '%common.core.namespace%\Serializer\View\RssViewHandler'

    # данный handler обрабатывает ответ клиенту в формате plist
    # данный формат в прилоежнии не используется но учитывается и работает
    rp_common.view_handler:
        parent: fos_rest.view_handler.default
        calls:
            - ['registerHandler', ['plist', ["@rp_common.plist_handler", 'createResponse']]]
            - ['registerHandler', ['rss', ["@rp_common.rss_handler", 'createResponse']]]
    
    # common bundles services
    rp_common.model_loader:
        class: '%common.core.namespace%\Loader\JSONModelLoader'
        arguments:
          - "@validator"
          - "@translator"

    # Simple Аутентификация по токену
    common.security.api_token_authenticator:
        class: Common\Security\ApiTokenAuthenticator
        public: false

    # UserProvider для вытаскивания аутентификации из MongoDB
    common.security.api_token_user_provider:
        class: Common\Security\ApiTokenUserProvider
        arguments:
            - '%mongodb.main_storage%'
            - '%mongodb.main_storage.database%'
            - '%mongodb.main_storage.user_collection%'
            - '%mongodb.token_storage%'
            - '%mongodb.token_storage.database%'
            - '%mongodb.token_storage.token_collection%'
        calls:
            - ['setTranslator', ["@translator"]]
