# Routing который формирует запрос для поиска мест
# по имени места или частичное совпадение в имени места
# пример запроса /api/search/v1/json/places/name
RPSearchBundle_search_places_byname:
    path: /v{_version}/{_format}/places/name
    defaults:
        _controller: RPSearchBundle:SearchPlaces:searchPlacesByName
        _version: 1
        _format: json
        template: "RPSearchBundle:SearchPlaces:searchplaces.html.twig" # обязательный параметр при передаче в формате HTML (frontend parts API)
    requirements:
        _method: (GET)
        _format: (json|xml|html|plist)
        _version: '1' # устанавливаем обязательную версию

# Routing который формирует запрос для поиска мест
# по имени места или частичное совпадение в имени места
# пример запроса /api/search/v1/json/places/name
RPSearchBundle_search_placetype_byname:
    path: /v{_version}/{_format}/places/type/name
    defaults:
        _controller: RPSearchBundle:SearchPlaces:searchPlaceTypeByName
        _version: 1
        _format: json
        template: "RPSearchBundle:SearchPlaces:searchPlaceTypeByName.html.twig" # обязательный параметр при передаче в формате HTML (frontend parts API)
    requirements:
        _method: (GET)
        _format: (json|xml|html|plist)
        _version: '1' # устанавливаем обязательную версию


# Routing который формирует запрос для поиска мест
# которые расположены в заданном городе по указанному радиусу
# пример запроса /api/search/v1/json/places/city/{cityId}
RPSearchBundle_search_places_bycity:
    path: /v{_version}/{_format}/places/city/{cityId}
    defaults:
        _controller: RPSearchBundle:SearchPlaces:searchPlacesByCity
        _version: 1
        _format: json
        template: "RPSearchBundle:SearchPlaces:searchplacescity.html.twig" # обязательный параметр при передаче в формате HTML (frontend parts API)
    requirements:
        _method: (GET)
        _format: (json|xml|html|plist)
        _version: '1' # устанавливаем обязательную версию
        cityId: \w+

# Routing который формирует запрос для поиска мест со скидками/бонусами
# пример запроса /api/search/v2/json/places/discount
RPSearchBundle_search_places_bydiscount:
    path: /v{_version}/{_format}/places/discount
    defaults:
        _controller: RPSearchBundle:SearchPlaces:searchPlacesByDiscount
        _version: 1
        _format: json
        template: "RPSearchBundle:SearchPlaces:searchplacesdiscount.html.twig" # обязательный параметр при передаче в формате HTML (frontend parts API)
    requirements:
        _method: (GET)
        _format: (json|xml|html|plist)
        _version: '1' # устанавливаем обязательную версию

# Routing который формирует запрос для поиска скидки по ID
# пример запроса /api/search/v1/json/discount/id/{discountId}
RPSearchBundle_search_discount_byid:
    path: /v{_version}/{_format}/discount/id/{discountId}
    defaults:
        _controller: RPSearchBundle:SearchPlaces:searchDiscountById
        _version: 1
        _format: json
        template: "RPSearchBundle:SearchPlaces:searchDiscountById.html.twig" # обязательный параметр при передаче в формате HTML (frontend parts API)
    requirements:
        _method: (OPTIONS|GET)
        _format: (json|xml|html|plist)
        _version: '1' # устанавливаем обязательную версию
        discountId: \w+
                
# Routing который формирует запрос для поиска одого места по ID
# пример запроса /api/search/v1/json/places/id/{placeId}
RPSearchBundle_search_places_byid:
    path: /v{_version}/{_format}/places/id/{placeId}
    defaults:
        _controller: RPSearchBundle:SearchPlaces:searchPlacesById
        _version: 1
        _format: json
        template: "RPSearchBundle:SearchPlaces:searchplaceid.html.twig" # обязательный параметр при передаче в формате HTML (frontend parts API)
    requirements:
        _method: (OPTIONS|GET)
        _format: (json|xml|html|plist)
        _version: '1' # устанавливаем обязательную версию
        placeId: \w+


# Routing который формирует запрос для поиска одого места по ID
# пример запроса /api/search/v1/json/places/id/{placeId}
RPSearchBundle_search_placetype_byid:
    path: /v{_version}/{_format}/places/type/id/{placeTypeId}
    defaults:
        _controller: RPSearchBundle:SearchPlaces:searchPlaceTypeById
        _version: 1
        _format: json
        template: "RPSearchBundle:SearchPlaces:searchPlaceTypeById.html.twig" # обязательный параметр при передаче в формате HTML (frontend parts API)
    requirements:
        _method: (OPTIONS|GET)
        _format: (json|xml|html|plist)
        _version: '1' # устанавливаем обязательную версию
        placeTypeId: \w+