RPSearchBundle_search_users:
    path: /v{_version}/{_format}/users
    defaults:
        _controller: RPSearchBundle:Search:searchUsers
        _version: 1
        _format: json
        template: "RPSearchBundle:Search:searchusers.html.twig" # обязательный параметр при передаче в формате HTML (frontend parts API)
    requirements:
        _method: (GET)
        _format: (json|xml|html|plist)
        _version: '1' # устанавливаем обязательную версию