# user account controller param
# to user controller actions you can call to url
# like /api/v1/json/search/user/поисковый_запрос
RPSearchBundle_search_user:
    path: /v{_version}/{_format}/search/user/{searchString}
    defaults:
        _controller: RPSearchBundle:Search:searchUser
        _version: 1
        _format: json
        template: "RPSearchBundle:Search:searchuser.html.twig" # обязательный параметр при передаче в формате HTML
    requirements:
        _method: GET
        searchString: \w+
        _format: (json|xml|html|plist)
        _version: '1' # устанавливаем обязательную версию