# Routing который формирует запрос для поиска пользователя
# по имени/фамилии пользователя (начало/середина имени/фамилии)
# пример запроса /api/search/v2/json/users/name
RPSearchBundle_search_users_byname:
    path: /v{_version}/{_format}/users/name
    defaults:
        _controller: RPSearchBundle:Search:searchUsersByName
        _version: 1
        _format: json
        template: "RPSearchBundle:Search:searchusers.html.twig" # обязательный параметр при передаче в формате HTML (frontend parts API)
    requirements:
        _method: (GET)
        _format: (json|xml|html|plist)
        _version: '1' # устанавливаем обязательную версию


# Routing который формирует запрос для поиска пользователя
# в определенном городе
# пример запроса /api/search/v1/json/cityname
RPSearchBundle_search_users_bycity:
    path: /v{_version}/{_format}/users/city
    defaults:
        _controller: RPSearchBundle:Search:searchUsersByCity
        _version: 1
        _format: json
        template: "RPSearchBundle:Search:searchusers.html.twig" # обязательный параметр при передаче в формате HTML (frontend parts API)
    requirements:
        _method: (GET)
        _format: (json|xml|html|plist)
        _version: '1' # устанавливаем обязательную версию