# Routing который формирует запрос поиска сообщений в чате
# пример запроса /api/search/v1/json/chat/messages
RPSearchBundle_search_chatmessage:
    path: /v{_version}/{_format}/chat/messages
    defaults:
        _controller: RPSearchBundle:SearchChatMessage:searchChatMessage
        _version: 1
        _format: json
        template: "RPSearchBundle:SearchChatMessage:searchChatMessage.html.twig" # обязательный параметр при передаче в формате HTML (frontend parts API)
    requirements:
        _method: (GET)
        _format: (json|xml|html|plist)
        _version: '1' # устанавливаем обязательную версию
        filterType: \w+