# Routing который формирует запрос вывода всех сообщений чата
# пример запроса /api/search/v1/json/chat/messages
RPSearchBundle_search_chatmessage:
    path: /v{_version}/{_format}/chat/messages/{chatId}
    defaults:
        _controller: RPSearchBundle:SearchChatMessage:getChatMessage
        _version: 1
        _format: json
        template: "RPSearchBundle:SearchChatMessage:searchChatMessage.html.twig" # обязательный параметр при передаче в формате HTML (frontend parts API)
    requirements:
        _method: (GET)
        _format: (json|xml|html|plist)
        _version: '1' # устанавливаем обязательную версию
        chatId: \w+

# Routing который формирует запрос поиска сообщений в чате
# пример запроса /api/search/v1/json/chat/search/messages
RPSearchBundle_search_search_chatmessage:
    path: /v{_version}/{_format}/chat/search/messages
    defaults:
        _controller: RPSearchBundle:SearchChatMessage:searchChatMessage
        _version: 1
        _format: json
        template: "RPSearchBundle:SearchChatMessage:searchChatMessage.html.twig" # обязательный параметр при передаче в формате HTML (frontend parts API)
    requirements:
        _method: (GET)
        _format: (json|xml|html|plist)
        _version: '1' # устанавливаем обязательную версию

# Routing который формирует запрос поиска сообщений в чате
# пример запроса /api/search/v1/json/chat/messages
RPSearchBundle_search_chats:
    path: /v{_version}/{_format}/chat/list
    defaults:
        _controller: RPSearchBundle:SearchChatMessage:searchChats
        _version: 1
        _format: json
        template: "RPSearchBundle:SearchChatMessage:searchChatMessage.html.twig" # обязательный параметр при передаче в формате HTML (frontend parts API)
    requirements:
        _method: (GET)
        _format: (json|xml|html|plist)
        _version: '1' # устанавливаем обязательную версию

# Routing который формирует запрос поиска одного чата
# пример запроса /api/search/v1/json/chat/id/{chatId}
RPSearchBundle_search_chatbyID:
    path: /v{_version}/{_format}/chat/id/{chatId}
    defaults:
        _controller: RPSearchBundle:SearchChatMessage:searchSingleChat
        _version: 1
        _format: json
        template: "RPSearchBundle:SearchChatMessage:searchChatMessage.html.twig" # обязательный параметр при передаче в формате HTML (frontend parts API)
    requirements:
        _method: (GET)
        _format: (json|xml|html|plist)
        _version: '1' # устанавливаем обязательную версию
        chatId: \w+

