# Routing который формирует запрос для поиска городов
# пример запроса /api/search/v1/json/city/name
RPSearchBundle_search_city_byname:
    path: /v{_version}/{_format}/city/name
    defaults:
        _controller: RPSearchBundle:SearchCity:searchCityByName
        _version: 1
        _format: json
        template: "RPSearchBundle:SearchCity:searchCityByName.html.twig" # обязательный параметр при передаче в формате HTML (frontend parts API)
    requirements:
        _method: (GET)
        _format: (json|xml|html|plist)
        _version: '1' # устанавливаем обязательную версию

# Routing который формирует запрос для поиска городов
# пример запроса /api/search/v1/json/city/name
RPSearchBundle_search_city_byid:
    path: /v{_version}/{_format}/city/id/{cityId}
    defaults:
        _controller: RPSearchBundle:SearchCity:searchCityById
        _version: 1
        _format: json
        template: "RPSearchBundle:SearchCity:searchCityById.html.twig" # обязательный параметр при передаче в формате HTML (frontend parts API)
    requirements:
        _method: (GET)
        _format: (json|xml|html|plist)
        _version: '1' # устанавливаем обязательную версию
        cityId: \w+

# Routing который формирует запрос
# на получение списка городов (порция через skip, count)
# пример запроса /api/search/v1/json/city/list
RPSearchBundle_search_city_list:
    path: /v{_version}/{_format}/city/list
    defaults:
        _controller: RPSearchBundle:SearchCity:searchCitiesList
        _version: 1
        _format: json
        template: "RPSearchBundle:SearchCity:citiesList.html.twig" # обязательный параметр при передаче в формате HTML (frontend parts API)
    requirements:
        _method: (GET)
        _format: (json|xml|html|plist)
        _version: '1' # устанавливаем обязательную версию

# Routing который формирует запрос
# на получение города по координатам
# пример запроса /api/search/v1/json/city/position
RPSearchBundle_search_city_position:
    path: /v{_version}/{_format}/city/position
    defaults:
        _controller: RPSearchBundle:SearchCity:searchCityByPosition
        _version: 1
        _format: json
        template: "RPSearchBundle:SearchCity:cityByPosition.html.twig" # обязательный параметр при передаче в формате HTML (frontend parts API)
    requirements:
        _method: (GET)
        _format: (json|xml|html|plist)
        _version: '1' # устанавливаем обязательную версию